### ISSUE TITLE
State of the Home Assistant API

### ISSUE THREAD

**Issue by totalitarian** [markvader/sonic_hacs#7]
Hi buddy, just got my sonic and i'm interested in the HA addon. Ant progress made or requirement for a beta tester?

**Comment by totalitarian** [comment]
Excellent! Just installed and pulling in my device worked first time

<img width="466" alt="image" src="https://user-images.githubusercontent.com/2385696/174151354-34443d67-bb45-46b3-8b6a-8b63de65450d.png">

**Comment by markvader** [comment]
Fantastic. Just wondering is your water pressure always so low? I was thinking that I would convert it to bar in the code and set this as standard rather than mbar as mine is typically 5000 mbar/5 bar (Users then have the option in home assistant to select a different unit (mbar, psi etc)).

**Comment by markvader** [comment]
> Ha, no it’s because it’s not physically installed yet. Waiting for the plumber to come tomorrow.

Thats good, i was trying to imagine, were you in a high mountain area in a hot part of the world where the water temperature was 24.6 degrees C.

Just to let you know, I added additional sensors last night. To update go to HACS, Click on Integrations, Scroll down and find the "Sonic (Beta) by @markvader", Click the 3 dots on the lower right corner and click "Redownload".  After a restart the new sensors should be available.

I'll close this issue for now, but if you have anything else just comment and i'll reopen it, or open a new issue with any specific problems.
